Repository Equinox-SS13/equinox-sojourn, pull requests merged in 2024-08, with the labels that each got.

#29 Re-enables taurs to the character creator.
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/sprite_accessories/_accessory_tail_taur.dm
  sojourn-station.dme
Labels: enhancement

#30 Fixes harmbatoning not having sufficient meaty thwackage.
  code/game/objects/items/weapons/tools/stunbatons.dm
Labels: bug

#32 QOL Fixes for Psionic Armor
  code/modules/psionics/psion_powers/armour_powers.dm
Labels: bug, enhancement

#20 Cyborg Movement Speed and Ladder Climbing Speed Rebalance
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/multiz/structures.dm
Labels: rebalance

#38 nanogate rebalance: variable speedup and regen
  code/__DEFINES/perks.dm
  code/datums/perks/nanogate.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/nanogate/powers/user.dm
  code/modules/projectiles/guns/mods/mods.dm
Labels: Enhancement, Rebalance

#40 mobs now respect armor when attacking
  code/modules/mob/living/living_defense.dm
Labels: Bugfix, Testmerge

#41 Rebranding to Equinox
  README.md
  icons/ss13_32.png
  icons/ss13_64.png
  interface/skin.dmf
Labels: Icons

#42 TGS DMAPI cleanup and addition of updater actions workflow
  .github/workflows/update_tgs_dmapi.yml
  code/__DEFINES/tgs.config.dm
  code/__DEFINES/tgs.dm
  code/game/world.dm
  code/modules/tgs/LICENSE
  code/modules/tgs/README.md
  code/modules/tgs/core/README.md
  code/modules/tgs/core/_definitions.dm
  code/modules/tgs/core/byond_world_export.dm
  code/modules/tgs/core/core.dm
  code/modules/tgs/core/datum.dm
  code/modules/tgs/core/tgs_version.dm
  code/modules/tgs/includes.dm
  code/modules/tgs/v3210/README.md
  code/modules/tgs/v3210/api.dm
  code/modules/tgs/v3210/commands.dm
  code/modules/tgs/v4/README.md
  code/modules/tgs/v4/api.dm
  code/modules/tgs/v4/commands.dm
  code/modules/tgs/v5/README.md
  code/modules/tgs/v5/__interop_version.dm
  code/modules/tgs/v5/_defines.dm
  code/modules/tgs/v5/api.dm
  code/modules/tgs/v5/bridge.dm
  code/modules/tgs/v5/chunking.dm
  code/modules/tgs/v5/commands.dm
  code/modules/tgs/v5/serializers.dm
  code/modules/tgs/v5/topic.dm
  code/modules/tgs/v5/undefs.dm
  sojourn-station.dme
  tgs_dmapi/tgs/v5/interop_version.dm
Labels: Server Ops

#44 Removes questionable language from perks.
  code/datums/perks/racial.dm
  code/modules/reagents/reagents/race.dm
Labels: Lore

#48 Blahaj
  code/game/objects/items/toys.dm
  code/game/objects/random/toys.dm
  icons/mob/items/lefthand_plushes.dmi
  icons/mob/items/righthand_plushes.dmi
  icons/obj/toy.dmi
Labels: New Content, Icons

#46 Vote to power the colony, take two.
  code/controllers/subsystems/voting/poll_types.dm
Labels: Enhancement

#50 Added ability to Direct Recycle
  code/game/machinery/autolathe/autolathe.dm
  icons/obj/machines/autolathe.dmi
Labels: Enhancement, Icons

#49 misc. fixes and exploit patches
  code/datums/autolathe/biomatter.dm
  code/datums/components/heat.dm
  code/game/objects/items/weapons/autolathe_disk/absolute_disks.dm
  code/modules/clothing/spacesuits/rig/modules/vision.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
  code/modules/projectiles/guns/energy/laser/concilium.dm
  code/modules/projectiles/guns/matter/launcher/nt_sprayer.dm
  code/modules/projectiles/projectile.dm
  code/modules/research/designs/rigmodules.dm
Labels: Enhancement, Bugfix

#51 Adding more alt styles to the Vector (acolyte)'s armor
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
Labels: Enhancement, Icons

#54 Cooking Fix - Certain produces now function properly for Cooking With Jane
  code/modules/cooking_with_jane/step_types/add_produce.dm
Labels: Bugfix

#59 Sanity exploit fixing
  code/datums/objective/individual_objective/individual_objective.dm
  code/modules/reagents/reagent_containers/syringes.dm
Labels: Bugfix

#60 Hotkey Additions and Help cleanup
  code/modules/mob/inventory.dm
  interface/interface.dm
  interface/skin.dmf
Labels: Documentation, Enhancement

#71 Gun Sprite Fix - Part One
  icons/obj/guns/energy/abnegate.dmi
  icons/obj/guns/energy/antebellum.dmi
  icons/obj/guns/energy/excubitor.dmi
  icons/obj/guns/energy/firestorm.dmi
  icons/obj/guns/energy/format_bound.dmi
  icons/obj/guns/energy/freezegun.dmi
  icons/obj/guns/energy/lancer.dmi
  icons/obj/guns/energy/makeshift_carbine.dmi
  icons/obj/guns/energy/martyr.dmi
  icons/obj/guns/energy/ntpistol.dmi
  icons/obj/guns/energy/ntpistol_bluecross.dmi
  icons/obj/guns/energy/nucgun.dmi
  icons/obj/guns/energy/nucgun2.dmi
  icons/obj/guns/energy/obrez_retro.dmi
Labels: Bugfix, Sprites
