Repository Equinox-SS13/equinox-sojourn, pull requests merged in 2024-09, with the labels that each got.

#75 Removes A Single Zero
  code/game/machinery/autolathe/fabricators.dm
Labels: Bugfix

#72 F + G Hotkeys: Intent cycling
  interface/interface.dm
  interface/skin.dmf
Labels: Enhancement

#77 Hopefully fixes (some) qdel runtimes at roundstart
  code/controllers/subsystems/migration.dm
Labels: Bugfix

#79 Fixes Klutz Mishaps Permanently Jamming Guns
  code/modules/projectiles/gun.dm
Labels: Bugfix

#58 Revert "mobs now respect armor when attacking"
  code/modules/mob/living/living_defense.dm
Labels: Bugfix

#89 Automatically label test merges
  .github/workflows/label_test_merges.yml
Labels: Server Ops
