Repository Equinox-SS13/equinox-sojourn, pull requests merged in 2025-03, with the labels that each got.

#133 Cherry-Pick 1
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/surgery/surgery.dm
Labels: Rebalance, Bugfix

#132 Change rules to a link system
  code/controllers/configuration.dm
  config/example/config.txt
  config/example/rules.html
  interface/interface.dm
Labels: Server Ops

#1 portals
  code/datums/position_point_vector.dm
  code/game/atoms.dm
  code/game/objects/effects/map_effects/map_effects.dm
  code/game/objects/effects/map_effects/perma_light.dm
  code/game/objects/effects/map_effects/portal.dm
  code/game/objects/effects/map_effects/screen_shaker.dm
  code/game/objects/effects/map_effects/sound_emitter.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob.dm
  icons/effects/map_effects.dmi
  sojourn-station.dme
Labels: Enhancement, Testmerge

#140 one line change to give borgs ooc notes
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Enhancement

#141 Prevents maxhealth reduction on level up
  code/modules/mob/mob.dm
Labels: Rebalance

#128 Upstream Update #1
  code/game/objects/items/devices/organ_module/active/armblades.dm
  code/game/objects/items/weapons/nt_melee.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/game/objects/items/weapons/tools/knifes_daggers.dm
  code/game/objects/items/weapons/tools/misc.dm
  code/modules/core_implant/cruciform/rituals/base.dm
  code/modules/core_implant/cruciform/rituals/path.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
  code/modules/psionics/ear.dm
  code/modules/psionics/psionic_items/psi_armor.dm
  code/modules/psionics/psionic_items/psi_catalysts.dm
  icons/obj/genetics/genetic_poster.dmi
  icons/obj/psionic/occmachinery.dmi
  maps/__DeepTunnels/map/_Nadezhda_Deep_Tunnels.dmm
  sojourn-station.dme
Labels: Enhancement, Map, New Content, Testmerge, Icons

#144 Sanctifier increases damage by flat 8, not 700%
  code/game/objects/items/weapons/tools/mods/mod_types.dm
Labels: Rebalance, Bugfix

#146 Introspective and Anomaly Hunter gives exact stats and perks on oddity
  code/datums/mob_stats.dm
  code/modules/sanity/inspiration_component.dm
Labels: Rebalance

#131 Crafting step is no longer globally shared
  code/datums/craft/recipe.dm
  code/datums/craft/step.dm
Labels: Rebalance, Bugfix, Testmerge

#127 Show extra inventory and recommendation favor threshold separately.
  code/modules/modular_computers/file_system/programs/generic/trade.dm
  code/modules/trade/datums/_trade_station.dm
  nano/templates/trade.tmpl
  nano/templates/trade_catalog.tmpl
Labels: Enhancement, Testmerge

#137 Add myosynaptizine, add organ revival chem - revitaline, rename and t…
  code/game/objects/items/weapons/storage/pouches.dm
  code/modules/mob/living/carbon/superior_animal/fungi/types/mushroom.dm
  code/modules/organs/organ.dm
  code/modules/reagents/reagent_containers/food/snacks/meat.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/reagents/recipes/recipes.dm
Labels: Enhancement, Rebalance, Testmerge

#151 Let slimes get markings - make markings transparent
  code/modules/client/preference_setup/general/06_furry.dm
  code/modules/organs/external/organ_icon.dm
Labels: Enhancement, Icons

#152 CtrlShiftClick to split stacks, cable coil examine + 120 rods
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/stack.dm
  code/modules/power/cable.dm
Labels: Enhancement, Refactor

#155 New seaslug-theme ears and tails
  code/modules/sprite_accessories/_accessory_ears.dm
  code/modules/sprite_accessories/_accessory_tail.dm
  icons/mob/sprite_accessory/ears.dmi
  icons/mob/sprite_accessory/tails.dmi
Labels: Icons

#159 Fixes Ammo Spam-Clicking
  code/modules/projectiles/ammunition.dm
Labels: Bugfix

#160 Fix In Lobby bug
  code/game/verbs/who.dm
Labels: Bugfix

#162 Fix map autodoc and add beep noise on scan
  code/game/machinery/autodoc.dm
  code/modules/surgery/autodoc.dm
Labels: Bugfix

#164 Pick a bunch of upstream fixes
  code/__HELPERS/mobs.dm
  code/datums/datum_click_handlers.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/doors/blast_door.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/gun_firemode.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/projectiles/projectile/fragment.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/reagents/reagent_containers/food/snacks/vendor_food.dm
Labels: Rebalance, Bugfix

#169 Laylas moyoverse 3
  code/modules/client/preference_setup/loadout/lists/footwear.dm
  code/modules/client/preference_setup/loadout/lists/gloves.dm
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/client/preference_setup/loadout/lists/uniforms.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/moyo.dm
  icons/inventory/feet/icon.dmi
  icons/inventory/feet/mob.dmi
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
  sojourn-station.dme
Labels: Enhancement

#163 Update contributing.md, readme and code of conduct
  README.md
  docs/CODE_OF_CONDUCT.MD
  docs/CONTRIBUTING.md
Labels: Documentation

#171 Arc Welder Desc Patch
  code/game/objects/items/weapons/tools/stunbatons.dm
Labels: Enhancement

#172 fixes material weapons
  code/game/objects/items/weapons/material/bats.dm
  code/game/objects/items/weapons/material/knives.dm
  code/game/objects/items/weapons/material/material_weapons.dm
Labels: Bugfix

#173 Mining Improvements
  code/__HELPERS/unsorted.dm
  code/game/mecha/equipment/tools/mining_tools.dm
  code/modules/mining/mine_turfs.dm
Labels: Enhancement

#175 Upstream Feature Port
  code/ZAS/Plasma.dm
  code/ZAS/Variable Settings.dm
  code/__DEFINES/items_clothing.dm
  code/__HELPERS/text.dm
  code/datums/craft/recipes/clothing.dm
  code/game/machinery/vendor/food_vendors.dm
  code/game/machinery/washing_machine.dm
  code/game/objects/effects/decals/crayon.dm
  code/game/objects/effects/melee.dm
  code/modules/client/preference_setup/loadout/lists/armament.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/void/void.dm
  code/modules/economy/os_cash.dm
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/seed.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seed_packets.dm
  code/modules/hydroponics/seed_storage.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/superior_animal/attack.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/types/hunter/hunter.dm
  code/modules/mob/living/carbon/superior_animal/human/subtype/voidwolf/voidwolf.dm
  code/modules/mob/living/carbon/superior_animal/roach/roach.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/fuhrer.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
  code/modules/mob/living/carbon/superior_animal/superior_defines.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite.dm
  code/modules/mob/living/carbon/superior_animal/termite/termite_no_despawn.dm
  code/modules/mob/living/carbon/superior_animal/vox/vox.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/reagents/reagents/other.dm
  code/modules/reagents/recipes/recipes.dm
  code/modules/scrap/oldificator.dm
  icons/effects/contamination.dmi
  icons/effects/mob_melee_animation.dmi
Labels: Enhancement, Rebalance, Sprites

#166 Port VRStation #8021 Character Preview
  code/_global_vars/mapping.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/preference_setup/augmentation/01_modifications.dm
  code/modules/client/preference_setup/general/02_body.dm
  code/modules/client/preference_setup/loadout/loadout.dm
  code/modules/client/preference_setup/preference_setup.dm
  code/modules/client/preference_setup/preview.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: Enhancement, Testmerge, Performance

#170 Turn on sprites caching
  code/modules/admin/verbs/appearance_testing.dm
Labels: Testmerge, Performance

#177 Enable Railing Buckling
  code/game/objects/structures/railing.dm
Labels: Enhancement
