Repository Equinox-SS13/equinox-sojourn, pull requests merged in 2025-02, with the labels that each got.

#98 De-LARPs paramedic.
  code/__DEFINES/jobs.dm
  code/game/jobs/job/medical.dm
  code/game/objects/items/oddities.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/client/preference_setup/loadout/lists/belt.dm
  code/modules/client/preference_setup/loadout/lists/factionsoteria.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/projectiles/guns/energy/laser/cog.dm
  code/modules/projectiles/guns/energy/projectile/sst.dm
  code/modules/projectiles/guns/energy/projectile/stun.dm
  maps/__Nadezhda/map/_Nadezhda_Colony_New.dmm
  tgui/packages/tgui/interfaces/IDCard.tsx
Labels: Enhancement, Testmerge

#97 matterforge now drops the power source item when deconstructed
  code/game/machinery/autolathe/matterforge.dm
Labels: Bugfix, Testmerge

#103 Nerfs holy oils
  code/game/objects/items/weapons/tools/mods/mod_types.dm
Labels: Rebalance, Testmerge

#104 Renames Vox Simplemobs
  code/modules/mob/living/carbon/superior_animal/vox/types/vox_types.dm
  code/modules/mob/living/carbon/superior_animal/vox/vox.dm
Labels: Enhancement, Testmerge

#109 Add missing female sprites + Port and re-sprite underwear
  icons/mob/human_races/r_fox.dmi
  icons/mob/human_races/r_lizard_white.dmi
  icons/mob/human_races/r_vulpkanin.dmi
  icons/mob/human_races/underwear.dmi
Labels: Enhancement, Testmerge, Sprites

#110 Awesome Dragonfruits Fluff Item
  code/modules/client/preference_setup/loadout/lists/fluff.dm
  icons/fluff/clothing_mob.dmi
  icons/fluff/fluff_items.dmi
Labels: Testmerge, Personal Fluff

#120 One line fix to make LOOC stop popping up the chat bubble
  code/modules/tgui_input/say_modal/modal.dm
Labels: Bugfix

#126 Update update_tgs_dmapi.yml
  .github/workflows/update_tgs_dmapi.yml
Labels: Server Ops

#124 New medical uniforms
  code/datums/outfits/jobs/medical.dm
  code/game/objects/items/weapons/storage/hardcases.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/clothing/accessories/holster.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/jobs/medsci.dm
  icons/inventory/accessory/icon.dmi
  icons/inventory/accessory/mob.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Lore, New Content, Icons

#129 New altstyle for a uniform
  code/modules/clothing/under/costume.dm
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Icons
